# Generated by Django 5.1 on 2024-09-20 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_customuser_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="phone_number",
            new_name="phone",
        ),
    ]
