# Generated by Django 5.1 on 2024-09-20 11:08

import account.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_rename_phone_number_customuser_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.utcnow)),
                (
                    "expires_at",
                    models.DateTimeField(default=account.models.get_expiration_date),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.customuser",
                    ),
                ),
            ],
            options={
                "db_table": "tokens",
            },
        ),
    ]
