# Generated by Django 5.1 on 2024-09-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
