# Generated by Django 5.1 on 2024-09-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_alter_token_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image_url", models.URLField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("book", "Books"),
                            ("clothes", "Clothes"),
                            ("home_decor", "Home Decor"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "products",
            },
        ),
    ]
