# Generated by Django 5.1 on 2024-09-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image_url",
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
